### ISSUE TITLE
Cookbook link ins't updated yet in yesodweb.com top bar

### ISSUE THREAD

**Issue by psibi** [yesodweb/yesodweb.com#16]
In yesodweb.com, the cookbook link isn't changed yet.

Either my [patch](https://github.com/yesodweb/yesodweb.com/pull/15) was wrong or the re-deployment hasn't been done ?

**Comment by snoyberg** [comment]
Looks like the Amazon melt down today killed off the old instances that
hadn't updated. Can you check that it's working?

**Comment by psibi** [comment]
This isn't yet working on yesdweb.com, although it works for me locally. My guess would be that you have to force recompile the entire site to make it work.

**Comment by snoyberg** [comment]
Which page are you seeing this on? And maybe you need to clear your cache, we were previously using 301 redirects

**Comment by psibi** [comment]
I did clear cache, but that doesn't seem to work for me. The redirect is working for me in other pages except the home page top bar: http://www.yesodweb.com/

Does the cookbook link on the top bar from that page correctly redirect you ?

**Comment by snoyberg** [comment]
Maybe the Docker image didn't push successfully (I had a similar problem
with haskellers.com), repushing now.

**Comment by snoyberg** [comment]
Alright, that should do it.

**Comment by psibi** [comment]
Phew, finally it works. Thanks!
