### ISSUE TITLE
http://www.yesodweb.com/ doesn't compress

### ISSUE THREAD

**Issue by knupfer** [yesodweb/yesodweb.com#20]
The gzipped version is less than half the size...

$ curl http://www.yesodweb.com/ --silent  --write-out "size_download=%{size_download}\n" --output /dev/null
size_download=13418
$ curl http://www.yesodweb.com/ --silent -H "Accept-Encoding: gzip,deflate" --write-out "size_download=%{size_download}\n" --output foo.html
size_download=13418

**Comment by snoyberg** [comment]
Compression added, thanks!
