### ISSUE TITLE
Article view on Pocket is a bit messy

### ISSUE THREAD

**Issue by giuliods** [yesodweb/yesodweb.com#28]
On yesodweb i can save, cancel and go to the articles, but internal view display a bunch of non-formatted code.

Pocket read correctly the title, the source and even the date, but don't load the content,replaced by probably part of the page code and json in a confused way

![Uploading Screenshot_2018-09-25 Pocket Keter It's Alive .png…](a screen of the article on keter)

**Comment by giuliods** [comment]
the link of the screenshot: http://horizonc.altervista.org/Screenshot_2018-09-25_Pocket_Keter_It_s_Alive_.png

**Comment by snoyberg** [comment]
I believe it's fixed now, though it looks like the old content is sometimes being cached.

**Comment by giuliods** [comment]
Yes, now it's working correctly. Thanks!
